apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: skilled-cattle-dotnet-basic
  janus-idp.io/tekton: skilled-cattle-dotnet-basic
  backstage.io/kubernetes-id: skilled-cattle-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: skilled-cattle-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
